version: '3.8'
services:
  nginx:
    image: nginx:1.19.9-alpine
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      - backend-network
networks: 
  backend-network:
    name: backend_network